# Copied from Zeste de Savoir,
# https://github.com/zestedesavoir/zds-site/blob/a16c5fc932b361cbee5c6e61b24167605e24cd8b/.travis.yml

dist: trusty

language: python

python:
  - 2.7

git:
  depth: 1

cache:
  apt: true
  directories:
    - $HOME/.texlive
    - $HOME/bin

install:
  - mkdir -p $HOME/bin
  - ./scripts/install_texlive.sh
  - export PATH=$HOME/.texlive/bin/x86_64-linux:$PATH
  - pip install Pygments
  - mkdir -p $HOME/.texlive/texmf-local/tex/latex/
  - cp zmdocument.cls $HOME/.texlive/texmf-local/tex/latex/
  - $HOME/.texlive/bin/x86_64-linux/texhash
  - rm zmdocument.cls

script:
    - make test
