# Copied from Zeste de Savoir,
# https://github.com/zestedesavoir/zds-site/blob/dev/.travis.yml

dist: trusty
sudo: required

language: bash

git:
  depth: 1

cache:
  apt: true
  directories:
    - $HOME/.texlive
    - $HOME/bin

install:
  - mkdir -p $HOME/bin
  - ./scripts/install_texlive.sh
  - export PATH=$HOME/.texlive/bin/x86_64-linux:$PATH

script:
    - make travis
